### ISSUE TITLE
How to extract string from JS that does not go directly through TranslateService?

### ISSUE THREAD

**Issue by sinedied** [biesbjerg/ngx-translate-extract#10]
Hello,
Thanks for the great tool, I'm missing an important use case though: how to extract arbitrary strings for translations, that does not go through the TranslateService direction but through an indirection?

I explain:
I would like to define strings to be translated, let's say in a constant file and then translate them later:
```js
var toBeTranslated = "Hello World"; // <-- how to mark this for extraction?
// ... later on
var translated = translateService.instant(toBeTranslated); // or .get...
```

In other translation tools, for example [Angular-gettext](https://angular-gettext.rocketeer.be/) which I used extensively with angular 1, it is possible tu use a "dummy" noop function to mark strings for extraction (in occurence, the `gettext()` function has this role).

If it's not already implemented, could you add support for this, either through a command-line option of directly included within `ng2-translate`?

**Comment by biesbjerg** [comment]
Any reason you're not just using the proper `translateService.instant` / `translateService.get` methods for all strings you want extracted/translated?

I get what you're saying about having a noop function to mark strings to be extracted, I just think it's somewhat of a dirty workaround and potentially confusing since the `toBeTranslated` variable isn't actually translated before being passed to `translateService`, so you could end up extracting strings that are never actually passed to `translateService`.

I'm not 100% against your suggestion, but I'm trying to keep this tool minimal / free of bloat as possible.

**Comment by sinedied** [comment]
@biesbjerg Yes we have many good reasons, here's a few use cases:

- translate keys from static/constant data models (which are not injected in Angular 2, like the `environment` constant)
- specify keys to be translated at a time when the translations are not loaded yet (in the routes for example, through a `{ data: { title: 'whatever' } }`)
- translate string-based enums

I understand that you want your tool to stay bloat-free, but this is really a common use case (see [gettext](https://www.gnu.org/software/gettext/manual/gettext.html) tools, they are the most widespread translations tools in the OSS community, so they are a good reference for essential translation feature/needs).

However, I don't really mind how the "mark string for extraction" feature is actually implemented: using a function is simple (in extraction means) and transparent performance-wise, but other solutions like using special comments could also work. 

As for extracting string which are not used, this is a developer responsibility, like other thinks alike, but a nice feature to help preventing (as well as potential helps for translators) would be to add a translation comment that indication the origin of the extracted string, see this example of an extracted string with angular-gettext tool:
```
#: main\screens\assets\assets.html:54
#: main\screens\overview\overview.html:99
msgid "All assets status"
msgstr "Etats des équipements"
```

**Comment by biesbjerg** [comment]
I just released a new version with an experimental AstServiceParser. In theory, it should be possible to support extracting variables passed to `TranslationService` without using marker functions, by looking up the variable value using the syntax tree. I probably won't be easy, but I think that would be the best approach

**Comment by sinedied** [comment]
@biesbjerg It's nice on the principle, but it won't work on many use case, this one for example:

> specify keys to be translated at a time when the translations are not loaded yet (in the routes for example, through a { data: { title: 'whatever' } })

If you do want to enable the dummy function extraction as a default I understand that, but why not add it an option then?

**Comment by sinedied** [comment]
Perfect 👍
Thanks a lot!
