### ISSUE TITLE
save multiple files issue

### ISSUE THREAD

**Issue by criniera** [biesbjerg/ngx-translate-extract#100]
In the ReadMe you mention 3 modes to save multiple files, however in my case only one is working. Can you reproduce this issue? I'm developing with angular 6.0.2 with angular-cli and visual studio code and i've just installed your lib with npm install @biesbjerg/ngx-translate-extract command.

> ngx-translate-extract -i ./src -o ./src/i18n/*.json
Gives error while saving (probably it tries to save a file named *.json)

> ngx-translate-extract -i ./src -o ./src/i18n/{da,en,fr}.json
Only one file is generated, it is named {da,en,fr}.json

> ngx-translate-extract -i ./src -o ./src/i18n/da.json ./src/i18n/en.json ./src/i18n/fr.json
This one is the only form working to save multiple files

**Comment by MartinMa** [comment]
I have the same issue. But luckily the third option you mentioned works as a workaround.

Related: #85

**Comment by clegeard** [comment]
I have the same problem. Any update?

**Comment by davemeech** [comment]
Myself as well, I tried approach #2 as it is much more clean and concise than #3 and got the same outcome.  #3 does work and I'll end up using that but am interested in knowing whether there will be an update/fix coming.

**Comment by Andrey-Pavlov** [comment]
Approach #2 returns file with the name '{en,es,ru,jp,no,by}.json'

**Comment by biesbjerg** [comment]
Method 1 and 2 is not supported on Windows, will add a note in next version.
