### ISSUE TITLE
Extracts only first component of file

### ISSUE THREAD

**Issue by bitbaggi** [biesbjerg/ngx-translate-extract#103]

**Comment by bitbaggi** [comment]
Change file "abstract-template.parser.js";
then multiple component-files extracts all components

`
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AbstractTemplateParser = (function () {
    function AbstractTemplateParser() {
    }
    AbstractTemplateParser.prototype._isAngularComponent = function (path) {
        return (/\.ts|js$/i).test(path);
    };
    AbstractTemplateParser.prototype._extractInlineTemplate = function (contents) {
        var matches = contents.match(/template\s*:\s*(["'`])([^\1]*?)\1/g);
        if (matches != null) {
            return matches.join();
        }
        return '';
    };
    return AbstractTemplateParser;
}());
exports.AbstractTemplateParser = AbstractTemplateParser;
`

**Comment by biesbjerg** [comment]
This is supported and have tests (maybe support was added after you created this issue)
