### ISSUE TITLE
Change newly extracted translation message value to it's key instead of empty string

### ISSUE THREAD

**Issue by atakchidi** [biesbjerg/ngx-translate-extract#109]
Currently default message for extracted translation message is empty string.
It should be translation key, or at least configurable.
There are number of reasons why this behaviour should be changed:
1) Empty string are really hard to track via simply viewing the app pages
2) It is a common use case when normal strings are used as translation keys instead of placeholders, (e.g "Hello world"  vs "APP_TITLE") in that case it may not even need to write translations for that language.
3) In case translation is not found it is logical to expect it to fallback to specified fallback message or at least print our translation key so that it could be easily noticed by dev or qa. And this behaviour is way more expected for any one who have worked with translations on diff languages /frameworks cause it is done that way almost everywhere.

**Comment by dario-frongillo** [comment]
there is news about this issue ?

**Comment by amoscatelli** [comment]
yea I am really interested in this too ...

**Comment by BenDevelopment** [comment]
Me too. @biesbjerg what do you think about that?

**Comment by jesusvallez** [comment]
@biesbjerg plis, what do you think about that?

**Comment by enzonotario** [comment]
Hi! Have anyone found a solution to this?

**Comment by atakchidi** [comment]
> 
> 
> Hi! Has anyone found a solution to this?

We solved this inside custom translations loader with simple if statement

**Comment by BenDevelopment** [comment]
@atakchidi what if you still want to use empty string as translation for specific terms ?

**Comment by atakchidi** [comment]
@BenDevelopment  than you are in trouble) Can be solved but kinda hacky with some sort of exclude list. That's exactly why I opened this issue.)

**Comment by jesusvallez** [comment]
https://github.com/jesusvallez/ngx-translate-extract

I tried to resolve this issue here :)

**Comment by enzonotario** [comment]
hey, thanks! but I just found this script https://github.com/biesbjerg/ngx-translate-extract/issues/40#issuecomment-370726708 and is the solution for me, since I need that the values were WRITTEN so I can translate them with BabelEdit

**Comment by biesbjerg** [comment]
I would suggest to use a custom loader (that's what I'm doing)

Here's an example:

```ts
import { HttpClient } from '@angular/common/http';

import { TranslateLoader } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

export interface TranslateHttpOptions {
	prefix?: string;
	suffix?: string;
	useKeyForEmptyTranslations?: boolean;
}

const defaultOptions: TranslateHttpOptions = {
	prefix: '/assets/i18n/',
	suffix: '.json',
	useKeyForEmptyTranslations: true
};

export class TranslateHttpLoader implements TranslateLoader {

	public constructor(protected http: HttpClient, protected options?: TranslateHttpOptions) {
		this.options = { ...defaultOptions, ...options };
	}

	public getTranslation(lang: string): Observable<Object> {
		return this.http.get(`${this.options.prefix}${lang}${this.options.suffix}`).pipe(
			map(translations => {
				if (this.options.useKeyForEmptyTranslations) {
					Object.keys(translations).forEach(key => {
						if (key.length && !translations[key].length) {
							translations[key] = key;
						}
					});
				}
				return translations;
			})
		);
	}
}
```

**Comment by biesbjerg** [comment]
Heads up: I'm working on this at the moment.

**Comment by smurfy** [comment]
@biesbjerg , cool thanks, i also need that feature. please also bear in mind, that if i use namespaced-json as format it should use the full key, not the intermediate key.. (``users.list.title``, instead of just ``title``)
We use Pootle to translate based on a "source" language considering out of these kind of keys.
