### ISSUE TITLE
Enhance Pipe pattern recognition

### ISSUE THREAD

**Issue by ugdpy** [biesbjerg/ngx-translate-extract#111]
Feature request.

I sometimes use this pattern to be able to display plural internationalization : 
```typescript
{{ requests.length > 1 ? 'FEATURE.REQUEST.PLURAL' : 'FEATURE.REQUEST' | translate}}
```
Theses translation key are not extracted.

Thanks for you time.

Keep it going, this is a really good tool you have here.

ugdpy

**Comment by JJBocanegra** [comment]
I'm having the same problem right now and it's conditioning my code, now I need to duplicate it :(

**Comment by CodySchaaf** [comment]
Or if not this, is there a recommended way to handle pluralization?

**Comment by buenjybar** [comment]
Why not using this [NgPlural](https://angular.io/api/common/NgPlural) convention?
