### ISSUE TITLE
Extracted 0 strings

### ISSUE THREAD

**Issue by ranouf** [biesbjerg/ngx-translate-extract#112]
Hi,

In my html I added i18n to all html block I want to translate, ex:

`<h2 class="tc-green-700" i18n>Select your product</h2>`

Then I execute :

`ng xi18n`

The file _src/messages.xlf_ was created.

Then I installed your package:

`npm install @biesbjerg/ngx-translate-extract@2.3.2 --save-dev`

(There is an issue with the lastest version, https://github.com/biesbjerg/ngx-translate-extract/issues/87, I had to take the version 2.3.2)

I added in packages.json:

>     "extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/ --clean --sort --format namespaced-json",

then I executed the command:

`npm run extract`

Result:

> Extracted 0 strings

Did I miss something? Is there a problem with the package?

**Comment by juristr** [comment]
Just had the exact same issue 😢. Using `v2.3.3` worked for me

**Comment by hamiarcher** [comment]
using 2.3.4 and having same issue.

**Comment by animbalk** [comment]
Same issue for me as well. I see blank Strings generated in JSON file using 2.3.4 version.  Thanks!

**Comment by jesusvallez** [comment]
Using 2.3.4 and I having same issue.

**Comment by jesusvallez** [comment]
Using 2.3.4 and having same issue

**Comment by biesbjerg** [comment]
You should use `translate` and not `i18n` when using `ngx-translate` and `ngx-translate-extract`, unless I'm misunderstanding?

**Comment by alydemah** [comment]
I'm also facing the same issue in latest ver.
