### ISSUE TITLE
Marker function _() not working in only one component

### ISSUE THREAD

**Issue by amruta-jv** [biesbjerg/ngx-translate-extract#113]
I'm using 2.3.4 version and _() marker function is failing to translate keys only in one component and not throwing any error. However, it works in all other components of an app. What could be reason for this? It's hard to debug when it doesn't throw an exception.

**Comment by biesbjerg** [comment]
The marker function doesn't do any actual translation, it just marks the string to let ngx-translate-extract know that it should extract it. You still have to pass it through `translateService`'s `get()` or `instant()` methods.
