### ISSUE TITLE
CRLFs in bin/cli.js, when installed with yarn

### ISSUE THREAD

**Issue by gflohr** [biesbjerg/ngx-translate-extract#114]
When you install the package with yarn instead of npm, the executable will use CRLF as line separator. Consequently`/usr/bin/env` will look for "node\r" as the script interpreter. The error message is:

```bash
$ yarn run  extract
yarn run v1.3.2
$ ngx-translate-extract --input ./src --output ./perl/po --clean --format pot
env: node\r: No such file or directory
error Command failed with exit code 127.
```

This could also be an issue with yarn but I suspect that you have the CRLFs in your local checkout.

I tried to  create a PR for this issue but the file is clean, when I clone the repository,  it just happens with yarn.

**Comment by gflohr** [comment]
If anybody else, runs into the same issue, the workaround is to specify the full command as a script:

```
"script": {
   "extract": "node  node_modules/ngx-translate-extract/bin/cli.js  OPTIONS"
} 
```

**Comment by biesbjerg** [comment]
I'm not using yarn and so far it seems no other have had issues. Closing as it seems you found a way to make it work :)

**Comment by antontemchenko** [comment]
@gflohr I also had this error.
Resolved thanks to [https://stackoverflow.com/a/30349952/4450072].

Solution is:
```
brew install dos2unix
sudo dos2unix node_modules/@biesbjerg/ngx-translate-extract/dist/cli/cli.js
```

**Comment by gflohr** [comment]
I can now explain the error.

If users don't read the README.md (like yours truly 🤭) carefully, then they install `ngx-translate-extract` and not `@biesbjerg/ngx-translate-extract`.

It doesn't matter whether you use `npm` or `yarn`, you always end up having installed the fork https://github.com/aamirvohra/ngx-translate-extract by @aamirvohra.  That fork contains a `bin/cli.js` with DOS line endings (CRLF).  While `npm`, strips off the DOS line ending from the shebang line, `yarn` copies it unmodified.

@aamirvohra: Do you have any particular reason to keep your fork around on npmjs.com? Okay, you have had over 1000 downloads this week, but I guess that they are 100 % accidents.  Your package seems to be just an old version that has zero commits.  Even your README is actually incorrect because it gives installation instructions for the "correct" package and not for your fork.

@biesbjerg: Maybe point that out a little bit more prominently in the README? It looks to me that a lot of your users are actually users of the fork without even noticing it.
