### ISSUE TITLE
Output json bad format

### ISSUE THREAD

**Issue by c4n4r** [biesbjerg/ngx-translate-extract#115]
Hello hello.
Maybe i'm doing something wrong, but I have a problem with my json export.

I only use the HTML to get my translations.

Here's an example  : 
`{{'Static.Loan' | translate}}`

Simple.

the result expected is  : 

`{
"Static" : {
"Loan" : "bla bla bla",
 "Broker" : "bla bla bla"
 ... 
}
}`

but, in output, here's what I have : 

` {"Static.Loan" : "bla bla bla", "Static.Broker": "bla bla bla" ... } `

Is there a way to get an output like I described?

Thank a lot!

**Comment by TekSiDoT** [comment]
You should use `-f namespaced-json`

**Comment by biesbjerg** [comment]
@TekSiDoT is right, closing.
