### ISSUE TITLE
Generic type 'Arguments' requires 1 type argument(s)

### ISSUE THREAD

**Issue by FinnStutzenstein** [biesbjerg/ngx-translate-extract#118]
Hi, I'm getting this error since this morning, when starting the application with start, or building it:
```
ERROR in node_modules/@biesbjerg/ngx-translate-extract/dist/cli/cli.d.ts(3,27): error TS2314: Generic type 'Arguments' requires 1 type argument(s).
```
Can someone help? Thanks!

**Comment by biesbjerg** [comment]
I can't reproduce this. Please try and remove your `node_modules` folder and run `npm install`. I'll reopen if it's still an issue.
