### ISSUE TITLE
Maintainance?

### ISSUE THREAD

**Issue by uded** [biesbjerg/ngx-translate-extract#120]
Is someone actually maintain this tool? It's super useful, but missing features and seems pretty dead for almost a year now...

**Comment by EnricoVogt** [comment]
@uded If you're willing to take care of it with me, I'd be willing to.

**Comment by sebastianzillessen** [comment]
@biesbjerg I am using this tool as well for various projects and I would like to start contributing. Could you reach out to me and we could discuss the options of becoming a contributor? 

Thanks so much,

Sebastian

**Comment by biesbjerg** [comment]
I'm working on an update and have already fixed quite a few bugs and added new features.

FYI: I'm considering changing the license to be free for personal / non-profit use, but paid for commercial use. 
That would give me an incentive to keep fixing bugs, adding new/requested features and do support.

**Comment by sebastianzillessen** [comment]
Well you could still allow contributions and let others help. I’m against changing licensing of already published software as it prevents people from using it.  But that is up to you (I would most likely fork the latest version which was still public to use and keep updating that one).
