### ISSUE TITLE
Extract namespaces into separate folders

### ISSUE THREAD

**Issue by limuxy** [biesbjerg/ngx-translate-extract#127]
Is it now possible to extract namespaces into separate folders? 
Say I have COMMON.NAME, EMPLOYEE.SALARY, etc, I need them be extracted into like:
- i18n
  - common
     - en.json
     - fr.json
  - emplyee
     - en.json
     - fr.json

**Comment by biesbjerg** [comment]
I'm not sure this fits within the scope of what ngx-translate-extract is supposed to do. You could do this yourself with some post processing in a custom script, if you really need to. Closing.
