### ISSUE TITLE
Sort is broken since 3.0.0 with namespaced-json format

### ISSUE THREAD

**Issue by bagage** [biesbjerg/ngx-translate-extract#131]
In 3.0.0, CLI option `--sort --format namespaced-json` is no longer working. Keys are sorted in random order.

**Comment by biesbjerg** [comment]
Hi,

After looking into this, I don't think it actually ever worked when using `namespaced-json`. 

`unflatten` messes with the ordered keys:
https://github.com/biesbjerg/ngx-translate-extract/blob/7d1bcd2a80eaa06dec278446bb2c86dfba0ec526/src/compilers/namespaced-json.compiler.ts#L20

**Comment by bagage** [comment]
Yes it was working previously, we are using it for one year now without any issue. Thanks for the fix!
