### ISSUE TITLE
Avoid non-npm dependency

### ISSUE THREAD

**Issue by davidkarlsen** [biesbjerg/ngx-translate-extract#132]
https://github.com/biesbjerg/ngx-translate-extract/blob/5d5b07ba2c3ac807819c11726f4fbb9c08f161b2/package.json#L63

can this dependency instead be a npm package?

**Comment by biesbjerg** [comment]
Not at the moment unfortunately

There's a bug in the original `flat` lib where key order is not kept when unflattening, breaking namedspaced-json compiler. There's a PR up to fix it but have not been merged: https://github.com/hughsk/flat/pull/84

**Comment by StevenLiekens** [comment]
Please use the github-URLs format rather than git:// URIs. https://docs.npmjs.com/files/package.json#github-urls

**Comment by biesbjerg** [comment]
Done.
