### ISSUE TITLE
Unable to install due to flat

### ISSUE THREAD

**Issue by Gumish91** [biesbjerg/ngx-translate-extract#137]
While trying to install via "npm i @biesbjerg/ngx-translate-extract" command

installation fails with following error:

error enoent undefined ls-remote -h -t git://github.com/lenchvolodymyr/flat.git

Is there any way around it ?

**Comment by MartinAskestad** [comment]
@Gumish91 I got it working by installing version 2.3.4, but otherwise same as you, error when installing due to trying to connect to github and doing something with flat.

**Comment by biesbjerg** [comment]
This should hopefully be fixed in v3.0.3 :)
