### ISSUE TITLE
Unable to install ngx-translate-extract package using "npm install" in clean docker environment (due to flat package dep)

### ISSUE THREAD

**Issue by bastibense** [biesbjerg/ngx-translate-extract#138]
Node: v10.16.3
NPM: v6.9.0

```
frontend_1     | npm ERR! path git
frontend_1     | npm ERR! code ENOENT
frontend_1     | npm ERR! errno ENOENT
frontend_1     | npm ERR! syscall spawn git
frontend_1     | npm ERR! enoent Error while executing:
frontend_1     | npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/lenchvolodymyr/flat.git
frontend_1     | npm ERR! enoent 
frontend_1     | npm ERR! enoent 
frontend_1     | npm ERR! enoent spawn git ENOENT
frontend_1     | npm ERR! enoent This is related to npm not being able to find a file.
frontend_1     | npm ERR! enoent 
```

Apparently the current release of ngx-translate-extract defines a dependency on a specific git commit for the `flat` package.

This causes trouble when running "npm install". Interestingly it works fine on Mac OS (Mojave) but in a clean Docker environment (node@10) it won't work.

Maybe using a more generic dependency string (instead of a link to a commit) would work better here and cause less problems?

Removing ngx-translate-extract from my project's package.json fixes the issue.

Would be awesome if this could be fixed so I can keep the dependency in the package.json.

Thanks

related #137 
related #132

**Comment by bastibense** [comment]
**A short update:**

Since I only need this tool once in a while to update the translation files, I had success by installing the package globally and run the `ngx-translate-extract` command without having to add a dependency to my project.

I know this is just a workaround, but in case someone else has issues, this might help.

**Comment by biesbjerg** [comment]
@bastibense did v3.0.3 not fix this for you? If not, I need to fork and publish the `flat` package for use with this lib.

**Comment by bastibense** [comment]
Just tried it again, but it seems that as soon as a dependency like `github:lenchvolodymyr/flat#ffe77ef"`is in the package.json, my setup goes bonkers.

**Comment by StevenLiekens** [comment]
@biesbjerg I recommend bundledDependencies over publishing a fork to the registry, if possible.

**Comment by biesbjerg** [comment]
@StevenLiekens good call! Didn't know about `bundledDependencies`. I just published a new released with `flat` bundled. Give it a try and let me know how it goes!
