### ISSUE TITLE
Support for strings using backticks as quotes

### ISSUE THREAD

**Issue by bastibense** [biesbjerg/ngx-translate-extract#139]
Not sure if this makes sense, but apparently ngx-translate-extract doesn't find strings from `instant()` calls if the argument for the call is a string that uses backticks.

Example:

    this.translate.instant(`GENERAL.CANCEL`)

Since these tend to be dynamic and their final value is determined at runtime, I'm not sure if this is a good idea.

Just noticed it when working on a project that has a policy of "backticks only" for strings and the markers weren't found (so I had to change the string quotes from backticks to regular quotes).

**Comment by biesbjerg** [comment]
Thanks for the issue! Fixed in 3.0.4 :)
