### ISSUE TITLE
Doesn't extract for multiple files using --output flag. Only for first of them.

### ISSUE THREAD

**Issue by VitalyVrublevskiy** [biesbjerg/ngx-translate-extract#141]
Step to reproduce: 

1. run one of the commands:

- ngx-translate-extract --input ./src --output ./src/i18n/{es,en}.json
- ngx-translate-extract --input ./src --output ./src/i18n/es.json ./src/i18n/en.json

Actual result: Changes saved only for first specified locale file

## More technical results:
OS: Mac OS

Output: 

>  ng2-translate-extract --dir ./src  -s --output ./src/assets/i18n/{en,es}.json
> 
> INFO: Extracting strings from '<path>/src'
> OK: * Extracted 11 strings
> OK: * Merged with 10 existing strings
> OK: * Saved to '<path>/src/assets/i18n/en.json'

**Comment by biesbjerg** [comment]
Please do `npm install @biesbjerg/ngx-translate-extract --save-dev`

Looks like you have `ng2-translate-extract` installed which is an old version.

**Comment by VitalyVrublevskiy** [comment]
Cool. Thanks a lot.
I get this instruction from really old [topic](https://github.com/ngx-translate/core/issues/401))

**Comment by biesbjerg** [comment]
Thanks. I've deprecated the package :-)

![image](https://user-images.githubusercontent.com/230182/65235702-70fd8f00-dad7-11e9-8a7b-e6f78df6bc5f.png)
