### ISSUE TITLE
Can't create custom marker

### ISSUE THREAD

**Issue by lubowiecki** [biesbjerg/ngx-translate-extract#142]
Hello, 
I would like to create custom marker method,
For examle:
```
function translationMarker<T extends string | string[]>(key: T): T {
  return key;
}
```

and then use it 
`ngx-translate-extract -m translationMarker`

I think i was possible before, but now it's not.

**Comment by biesbjerg** [comment]
Please see the readme: https://github.com/biesbjerg/ngx-translate-extract/blob/master/README.md#marker-function

**Comment by lubowiecki** [comment]
I would like to add some additional behavior to that marker function. That's why I wan't to import it from different place. Right now it is hardcoded to let import only directly from your package.

**Comment by biesbjerg** [comment]
Please elaborate. What kind of behavior?

**Comment by lubowiecki** [comment]
I want to add typechecking to marker function based on autogenerated interface (for example with quicktype package).

example:
```
interface Translations { 
	'navbar.links.validation.text': string; 
	'pages.validation.meta.description': string;
	'pages.validation.meta.title': string;
}

type TranslationKey = keyof Translations;

function marker(key: TranslationKey): TranslationKey {
	return key
}

const text = marker('navbar.links.validation.text')
```

**Comment by biesbjerg** [comment]
What do you think about doing it like this, which should already be supported:

```ts
interface Translations { 
	'navbar.links.validation.text': string; 
	'pages.validation.meta.description': string;
	'pages.validation.meta.title': string;
}

type TKeys = keyof Translations;

const text = marker<TKeys>('navbar.links.validation.text')
                   ~~~~~~~ <--- Add type info
```

I'm hesitant to add the custom marker back, as I'm trying to minimize the number of arguments of this tool to keep easy to use and maintain.

**Comment by lubowiecki** [comment]
Yeah it should work. Do you think that same generic could be used in translate pipe?
