### ISSUE TITLE
When translate is used as a directive, ngx-translate-extract does not find the key(s).

### ISSUE THREAD

**Issue by troymjones** [biesbjerg/ngx-translate-extract#149]
Version 2.3.4 used to support finding keys when the translate attribute is actually included as a directive. `[translate]="'MY_KEY'"` would be an example that worked before, but no longer does since upgrading to 3.x.x or 4.x.x. 

If I change it to not use the directive like this: `translate="MY_KEY"` it obviously works. ngx-translate clearly intends to support the directive version as found here: https://github.com/ngx-translate/core#4-use-the-service-the-pipe-or-the-directive.

Here would be a test that I would expect to pass (but does not) in the current file directive.parser.spec.ts:

```
it('should extract translate directive value as key when provided', () => {
	const contents = '<div [translate]="\'MY_KEY\'"></div>';
	const keys = parser.extract(contents, templateFilename).keys();
	expect(keys).to.deep.equal(['MY_KEY']);
});
```

Let me know if you need any additional information.

**Comment by SteffenSchwaiger** [comment]
It seems like the angular compiler treats plain attributes differently than input and output bound ones.

```ts
export declare class Element implements Node {
    ...
    attributes: TextAttribute[];
    inputs: BoundAttribute[];
    outputs: BoundEvent[];
    ...
}
```
[Angular Compiler Source Code](https://github.com/angular/angular/blob/49be32c9315a5c7ff155c5b88191e504006f595b/packages/compiler/src/render3/r3_ast.ts#L78-L92)

Therefore this package needs support for translate keys which are passed via a input binding.
I implemented that functionality and created a PR (#190).

@biesbjerg what do you think of these changes? I am not to familiar with angular compiler stuff.

**Comment by biesbjerg** [comment]
Hello! Thank you for the PR!

I've had some time to look into this and added support in https://github.com/biesbjerg/ngx-translate-extract/commit/85cd1e4a4683a2569de6bc072dc3849bc4c35328.

Will be released in the next version :-)

**Comment by gstercken** [comment]
@biesbjerg Do you think it would be possible to release a minor version that includes this fix already anytime soon? Our project has quite a few occurrences of the translate directive as a bound attribute, and they are currently stripped every time `ngx-translate-extract` is run. Thanks! ;-)
