### ISSUE TITLE
Not extracting all translations

### ISSUE THREAD

**Issue by patrickrioux** [biesbjerg/ngx-translate-extract#154]
Hi,

I would like to use this tool to extract all the translations and compare with the current i18n file we have. Not all developers are removing them and the file becomes messy.

How difficult it will be to change the tool to retrieve such translation key formats?

`<h3>{{ (isNew ? 'ADD-ASSESSMENT' : isDeleted ? 'VIEW-ASSESSMENT' : 'EDIT-ASSESSMENT' ) | translate }}</h3>`

**Comment by uragun91** [comment]
It seems that it doesn't extract translations with pipe

**Comment by mrambow** [comment]
You could just use a variable and extract the key outside the html:

`<h3>{{ someVar | translate }}</h3>`
and 
`someVar = isNew ? marker('ADD-ASSESSMENT') : isDeleted ? marker('VIEW-ASSESSMENT') : marker('EDIT-ASSESSMENT')`

**Comment by chancezeus** [comment]
On the other hand (however it's more "expressive" and thus a bit heavier (cpu wise), you can also do this:

`<h3>{{ isNew ? ('ADD-ASSESSMENT' | translate) : isDeleted ? ('VIEW-ASSESSMENT' | translate) : ('EDIT-ASSESSMENT' | translate) }}</h3>`

or use "ngIf" instead, like
```
<h3>
  <ng-container *ngIf="isNew; else notNew">
    {{ 'ADD-ASSESSMENT' | translate }}
  </ng-container>
  <ng-template #notNew>
    <ng-container *ngIf="isDeleted; else notDeleted">
      {{ 'VIEW-ASSESSMENT' | translate }}
    </ng-container>
    <ng-template #notDeleted>
      {{ 'EDIT-ASSESSMENT' | translate }}
    </ng-template>
</ng-template>
</h3>
```

Both of these variants should work properly with this package and it saves you an additional variable (and possibly additional logic) in the controller.

Which variant you choose depends on your personal preference.
