### ISSUE TITLE
Cannot extract when array is given

### ISSUE THREAD

**Issue by OysteinAmundsen** [biesbjerg/ngx-translate-extract#160]
Given the following code (which is allowed by @ngx-translate): 
```
this.translate.instant(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']);
```
Running the extractor...
```
ngx-translate-extract -i ./src/app -o ./src/i18n/template.json ./src/i18n/no.json ./src/i18n/en.json --clean --sort
```
... will produce nothing. No trace of the keys in the array. I have to split the array up into individual calls (one per array entry) in order for the extractor to produce entries.

**Comment by biesbjerg** [comment]
Can you please provide a full example? There are tests passing for this.

https://github.com/biesbjerg/ngx-translate-extract/blob/master/tests/parsers/service.parser.spec.ts#L94
