### ISSUE TITLE
2+ exported classes in one TS file : Translations are extracted

### ISSUE THREAD

**Issue by jscti** [biesbjerg/ngx-translate-extract#162]
The lib doesn't extract translations when a single typescript file contains 2 different exported classes.

Scratched my head some time before understanding that ^^ 

For now I'll separate each class in a file but it's quite a weird/silent bug

**Comment by biesbjerg** [comment]
There's a passing test for that here: https://github.com/biesbjerg/ngx-translate-extract/blob/608c4e8e2260d9bb443bd5600bfa4e6e0d70e46c/tests/parsers/service.parser.spec.ts#L228-L260
