### ISSUE TITLE
Cannot extract from TranslateService

### ISSUE THREAD

**Issue by Tawsif** [biesbjerg/ngx-translate-extract#169]
Not able to extract strings from TranslateService by using any methods get instant , etc none of them are working

**Comment by jochenjonc** [comment]
Hi @Tawsif,

Is was able to fix this issue by manually adjusting the entry of ngx-translate-extract in the package-lock.json. I replaced it again with a version that used to work.
After that, I removed my node_modules folder and run npm install.

To be honest, not all is fixed. Some keys are not extracted and I'm looking into it a bit more.

Below is an extract of my package-lock.json, the first is the broken one, the second is the one that solved most issues. You can also see the differences [here](https://www.diffchecker.com/nn0jM39R).

This is the same issue as  #166.

**Comment by biesbjerg** [comment]
@Tawsif Can you please add an example of how you're using `TranslateService`? (Full file)

**Comment by asmaus** [comment]
In angular 9.0.7 `ngx-translate-extract` does not work.

**Comment by biesbjerg** [comment]
What “does not work”?

I have an app on 9.0.7 and ngx-translate-extract seems to be working fine. I don’t see how the version of Angular used in the app extracting strings from is relevant either and could possibly be at fault?

**Comment by asmaus** [comment]
Hi @biesbjerg,

I have a script that works up to version 4.2.0 of @biesbjerg/ngx-translate-extract. With any later version it gives me an error when executing extract


````cmd
expandPattern(...).map(...).flat is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aubay@1.0.0 extract: `ngx-translate-extract -i ./src -o ./src/assets/i18n/i18n.general/ca.json ./src/assets/i18n/i18n.general/es.json ./src/assets/i18n/i18n.general/en.json ./src/assets/i18n/i18n.general/fr.json -c -s -f namespaced-json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aubay@1.0.0 extract script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sascha1337** [comment]
same failure as @asmaus here. would be nice 2 see some solution

**Comment by biesbjerg** [comment]
I need a way to reproduce it to be able to fix it. Please provide a repository and instructions to reproduce.

**Comment by sascha1337** [comment]
weirdly its working for me now, i had an empty .json file in i18n folder, which i have changed to be at least {}, and now its working for me.

**Comment by biesbjerg** [comment]
I think people are talking about different errors here.

I've done some testing and found that Node v11.5.0 or newer is required (to support `array.flat()`) which is reflected in v6.0.1

Please delete your `node_modules` and do `npm install` (with at least ngx-translate-extract@6.0.1) and try again. If it doesn't work please create a new ticket describing how to reproduce your problem.

**Comment by biesbjerg** [comment]
@sascha1337 I made some improvements on the situation you ran into, too:

![image](https://user-images.githubusercontent.com/230182/77534124-6661ef00-6e98-11ea-9781-304f3d9dc308.png)

**Comment by sascha1337** [comment]
@biesbjerg thats amazing, thanks, will help other ppl too

**Comment by asmaus** [comment]
Good job @biesbjerg
Working perfectly with Node 12.16.1

**Comment by sascha1337** [comment]
Amazing, good it works for you @asmaus

**Comment by ViieeS** [comment]
> I've done some testing and found that Node v11.5.0 or newer is required (to support array.flat()) which is reflected in v6.0.1

@biesbjerg How about not using `Array.prototype.flat()`? There are [alternatives](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Alternatives).

I guess a lot of people use Node v10, it's [LTS](https://nodejs.org/en/about/releases/) 'till 2021-04-30.
