### ISSUE TITLE
Is it possible to only add newly found translations

### ISSUE THREAD

**Issue by MarkVink** [biesbjerg/ngx-translate-extract#170]
I've noted issue #10 and the option to use a marker to inform this library about keys that should be extracted. However, in my use case, I have keys in my translation files that are just not present anywhere in my frontend project. 

For example;
- In my project, I use @gilsdav/ngx-translate-router which has an integration with ngx-translate to translate parts of URL structure.
- In my project, I translate exception codes that are raised on the backend API. 

In both these use cases, the translation keys do not exist in the frontend project, and therefore they are removed from my translation files when using this library. I think it would be very useful to have the option to not discard missing terms, but only adding newly found ones instead.

**Comment by biesbjerg** [comment]
String not present in project are only removed when using `--clean, -c` (Remove obsolete strings after merge) option. Sound like you're using that argument, if you're seeing strings being removed from your translation files after running extraction.

**Comment by MarkVink** [comment]
You are right, I was using the '--clean' option.
