### ISSUE TITLE
npm ERR! missing script: ngx-translate-extract

### ISSUE THREAD

**Issue by rattkin** [biesbjerg/ngx-translate-extract#178]
then I try to run the script:
`npm run ngx-translate-extract`
I get this message:
`npm ERR! missing script: ngx-translate-extract`

I did the install steps:

1. npm install @biesbjerg/ngx-translate-extract --save-dev
2. Add a script to your project's package.json: 
"scripts": {
  "extract-i18n": "ngx-translate-extract --input ./src --output ./src/assets/i18n/strings.json --key-as-default-value --clean --sort --format namespaced-json"
}

I don't know whats wrong, other scripts like npm start or npm build, npm test all work fine.

**Comment by ivansci** [comment]
Same problem, its the only script not working.

Error:
'ngx-translate-extract' is not recognized as an internal or external command,operable program or batch file.

"@biesbjerg/ngx-translate-extract": "^6.0.3",
"@angular/cli": "~9.0.7",

**Comment by biesbjerg** [comment]
You are defining the script name as `extract-i18n`, so the correct way to run it would be `npm run extract-i18n`.

**Comment by rattkin** [comment]
Yes thank you! my mistake.

**Comment by zavakare** [comment]
HI, I just began to install this and I get the same error. I am calling the right command.

**Comment by rattkin** [comment]
What is the line you added to in package.json?

**Comment by zavakare** [comment]
@rattkin 
I have tried:
"extract-translations": "ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json --clean --sort --format namespaced-json --marker _"

"extract-translations": "ngx-translate-extract --input ./src --output ./src/assets/i18n/ --clean --sort --format namespaced-json --marker _"

"extract-translations": "npm run ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json --clean --sort --format namespaced-json --marker _"

then on my command line I put==>  npm run extract-translations
I get the missing script error


When I run the command through my terminal:
npm run ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json --key-as-default-value --clean --sort --format namespaced-json

I get the missing script error

**Comment by rattkin** [comment]
![image](https://user-images.githubusercontent.com/910080/81434728-f1f0c000-9166-11ea-8957-b45e3d752456.png)
the blue part is the name of the script. You should run: npm run extract-translations

**Comment by zavakare** [comment]
@rattkin  yes that is what I did too

**Comment by zavakare** [comment]
Could it be I need to install some dependencies?
![image](https://user-images.githubusercontent.com/16713500/81435963-4166ca00-912e-11ea-925e-7798d3a1b3a6.png)

**Comment by rattkin** [comment]
I have the line in the picture I posted above in my package.json.
Then I run in terminal:
npm run extract-translations

**Comment by zavakare** [comment]
I have the following:
![image](https://user-images.githubusercontent.com/16713500/81742996-8fe5d280-9466-11ea-83e4-f9e6360c349c.png)
and extracting the translation is not working for me. It tells me I have a missing script error.

**Comment by rattkin** [comment]
@zavakare that does not look like contents of file package.json. please look into package.json file. You will find it in the root of the project.

**Comment by zavakare** [comment]
I got it to work with a different @ngx-translate-extract version 4.2.0 however i get another error now

**Comment by zavakare** [comment]
> @zavakare that does not look like contents of file package.json. please look into package.json file. You will find it in the root of the project.

Yes it is not my package.json file. It is my version information.

**Comment by pinguinosod** [comment]
This workaround fixed it for me:

* Add to scripts in package.json:
`"extract-i18n": "node node_modules/@biesbjerg/ngx-translate-extract/bin/cli.js --input ./src --output ./src/assets/i18n/en.json ./src/assets/i18n/de.json --format=namespaced-json --clean --sort",`
* Then execute `npm run extract-i18n`

**Comment by melhergui** [comment]
I am receiving this error. Can someone help me? Ionic v7 and node 20.10 LTS/iron

My package.json has this script entry:

"extract-i18n": "node node_modules/@biesbjerg/ngx-translate-extract/bin/cli.js --input ./src --output ./src/assets/i18n/strings.json --format=namespaced-json --clean --sort"

And I am running:

npm run extract-i18n

> node node_modules/@biesbjerg/ngx-translate-extract/bin/cli.js --input ./src --output ./src/assets/i18n/strings.json --format=namespaced-json --clean --sort

node:internal/modules/cjs/loader:1204
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/melhergui/www/smartrights.com/atila/smartright/node_modules/@angular/compiler/fesm2015/compiler.mjs not supported.
Instead change the require of /home/melhergui/www/smartrights.com/atila/smartright/node_modules/@angular/compiler/fesm2015/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/melhergui/www/smartrights.com/atila/smartright/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/pipe.parser.js:3:20) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.10.0
