### ISSUE TITLE
Regression: keys are not found in ternery expression

### ISSUE THREAD

**Issue by Dassderdie** [biesbjerg/ngx-translate-extract#179]
The following worked in 4.2 but doesn't anymore on 6.0.3:
```
{{
    condition
        ? ('key1' | translate)
        :  aVariable
}}
```
-> 'key1' got correctly extracted in 4.2 
-> with 6.0.3 nothing gets extracted

**Useful for a Workaround:**

```
{{
    (condition
        ? 'key1'
        :  'key2') | translate
}}
```
-> 'key1'  and 'key2' now get correctly extracted

**Comment by bartholomej** [comment]
@Dassderdie I believe this is a feature and also _not mentioned_ **breaking change** (cc @biesbjerg) in v5.x.x 
https://github.com/biesbjerg/ngx-translate-extract/commit/a17ad9c37369fcbec2be7a5921b056e81487f671 #111 #154

**Comment by mtraynham** [comment]
Also happens in the case where only one side of the condition would be translated.

```
[matTooltip]="conditions ? ('key1' | translate) : ''"
```

**Comment by biesbjerg** [comment]
Ideally it should work, even if translate pipe is part of the true/false expression. Marking as a bug.

**Comment by sod** [comment]
the issues appears when going from 4.2.0 to 5.0.0. So any of those commits: https://github.com/biesbjerg/ngx-translate-extract/compare/v4.2.0...v5.0.0 introduced it.

**Comment by sod** [comment]
you could try https://github.com/biesbjerg/ngx-translate-extract/pull/185 if it fixes all your regressions. You have to clone the branch, build with `npm run build` and then link into your project via `npm link ../../path/to/clone`

**Comment by bartholomej** [comment]
@sod I confirm. It works with old and new ternary expressions. Great work!
