### ISSUE TITLE
Getting error when i run "npm run extract"

### ISSUE THREAD

**Issue by gonadn** [biesbjerg/ngx-translate-extract#180]
HI,

Iam getting an error: `expandPattern(...).map(...).flat` is not a function when i run npm run extract...

`"extract": "ngx-translate-extract --input ./src/app/ --output ./src/assets/i18n/*.json --clean --sort --format namespaced-json"`
![image](https://user-images.githubusercontent.com/3224441/78817666-c649b100-79d3-11ea-8c8e-4dd7cb591936.png)

**i18n Language files**:
![image](https://user-images.githubusercontent.com/3224441/78817740-e5e0d980-79d3-11ea-9a0e-d67df6f39805.png)

**Comment by biesbjerg** [comment]
Node 11 or newer is required. Update your node version! :-)
