### ISSUE TITLE
why all json is empty values?

### ISSUE THREAD

**Issue by nbedevi** [biesbjerg/ngx-translate-extract#187]
code snippet `  <div class="not-found-title">{{ '404' | translate }}</div>`
JSON snippet `{"404": ""}`

scripts 
```
"i18n:init": "ngx-translate-extract --input ./src --output ./src/assets/i18n/template.json --key-as-default-value --replace --format json",
    "i18n:extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/{en,ar}.json --clean --format json"
```

what the wrong in my generator?

**Comment by SteffenSchwaiger** [comment]
I can reproduce this behaviour on a windows machine when using the "brace expression" notation (`../{en,ar}.json`) above. This notation won't work (properly) on windows machines and will only create one single file with the name`{en,ar}.json`. In this file all values are empty.

If I use the following notation two files are generated. See the two seperatly specified output paths.
```json
"i18n:extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json ./src/assets/i18n/ar.json --clean --format json"
```

The first of these files contains the correct default values and the second one is empty. When you configure the first file/language to be your ngx-translate default language, the fallback behaviour should lead to your expected result.
```ts
// this language will be used as a fallback when a translation isn't found in the current language
translate.setDefaultLang('en');
```
[ngx-translate](https://github.com/ngx-translate/core#methods)
