### ISSUE TITLE
spaces in translation causes problems when switching languages

### ISSUE THREAD

**Issue by robstoll** [biesbjerg/ngx-translate-extract#212]
relates to #175 I guess. 
I have finally updated to 7.0.0 and tried out if it works as it should following the problem
```
<p translate>
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore 
  et dolore magna   aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
</p>
```
the problem are the leading and ending spaces. For whatever reason the translate does not work this way, in certain scenarios:
- if I enter directly the url to the site (if I navigate away and come back then it works)
- if I chose the main language in which the key is null in the .json file (in my case DE) it switches to DE but I cannot switch back to EN, the translate somehow does not kick in.

note that it does not happen if there is no space at the beginning and end of the tag, then every scenario above works as it should. I.e. if it is as follows:
```
<p translate>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore 
  et dolore magna   aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
```

**Comment by biesbjerg** [comment]
This sounds more like a problem with `ngx-translate` to me?

**Comment by robstoll** [comment]
You're right, the extraction is exactly the same for both shown cases. Going to open an issue at ngx-translate
