### ISSUE TITLE
When using a binding value, is there a way to extract it?

### ISSUE THREAD

**Issue by playkang** [biesbjerg/ngx-translate-extract#213]
```
<nav *ngFor="let board of board">
   {{board.board_name | translate}}
</nav>
```

I am using a value binding like this.

In this case, extraction does not work. Is there a way?

**Comment by Franky238** [comment]
yes, this is missing.

**Comment by buchtadan** [comment]
@playkang where did you get your values from?

If those are hardcoded values in your controller or so take a look at https://github.com/biesbjerg/ngx-translate-extract-marker 
The Documentation is here [marker-function](https://github.com/biesbjerg/ngx-translate-extract#marker-function)
There can you write something like 
```
const boards = [
  {board_name: marker('FOO'), board_desc: 'Lorem ipsum dolor sit amet'},
  {board_name: marker('BAR'), board_desc: 'consectetur adipiscing elit'}},
  ...
  {board_name: marker('BAZ'), board_desc: 'sed do eiusmod tempor incididunt'}},
];
```
The Values in the marker will be extracted.

If you get your values eg. from a rest interface you have to deposit your values somewhere.
Maybe it's a solution to create an enum or so and match those values from custom pipe.
Take a look at this [approach](https://github.com/biesbjerg/ngx-translate-extract/issues/211#issuecomment-694702105), maybe it helps you.

**Comment by playkang** [comment]
These values are not hardcoded. I will find another way. Thank you.
