### ISSUE TITLE
Typesctipt 4 support

### ISSUE THREAD

**Issue by commercialsuicide** [biesbjerg/ngx-translate-extract#214]
Angular 10 requires Typescript version 4, and when trying to migrate from Angular 9 to Angular 10 via `ng update @angular/core @angular/cli` we get an error:

```
Package "@biesbjerg/ngx-translate-extract" has an incompatible peer dependency to "typescript" (requires "^3.0.0", would install "4.0.3").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/01/xf4fvdkd6s71z6bxx9xnltd40000gn/T/ng-k0IYCF/angular-errors.log" for further details.
```

Tested on the latest currently available **@biesbjerg/ngx-translate-extract** version **7.0.2**.

Is it possible to add Typescript 4 support?

**Comment by andreyjamer** [comment]
I created [PR](https://github.com/biesbjerg/ngx-translate-extract/pull/209) to fix this. Waiting for approval and merge.

**Comment by biesbjerg** [comment]
Hi,

This is added in newest release.

**Comment by andreyjamer** [comment]
Many thanks!
