### ISSUE TITLE
what the different

### ISSUE THREAD

**Issue by WuglyakBolgoink** [biesbjerg/ngx-translate-extract#216]
between `"i18n:init"` and `"i18n:extract"` tasks?

```
...
"scripts": {
  "i18n:init": "ngx-translate-extract --input ./src --output ./src/assets/i18n/template.json --key-as-default-value --replace --format json",
  "i18n:extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/{en,da,de,fi,nb,nl,sv}.json --clean --format json"
}
...
```

**Comment by biesbjerg** [comment]
`i18n:init` inits a new language template with extracted keys, where key values are the same.
`i18n:extract` extracts keys and merges with multiple language files while removing obsolete keys.

**Comment by WuglyakBolgoink** [comment]
@biesbjerg but for what I need template? or do I need this? Because `"i18n:extract"`-task doesn't use this file...

**Comment by biesbjerg** [comment]
You might not need it. 

I use it to create an initial template where values are the same as the keys which is required to create a project in the service where I purchase my translations (ICanLocalize).

**Comment by WuglyakBolgoink** [comment]
@biesbjerg ok! thx!

**Comment by marie-dk** [comment]
@WuglyakBolgoink thank you for asking this question. I was wondering about that myself. 
I think it would be a good idea to add this to the documentation.
