### ISSUE TITLE
Make the spacer value configurable in the namespaced json compiler

### ISSUE THREAD

**Issue by paulmfischer** [biesbjerg/ngx-translate-extract#22]
Currently working on a project where we use this tool to help us extract keys in a large application and we use code styles to enforce some rules on our files.  One is that we use spaces instead of tabs so it would be nice if we could pass in an option for the tool to use spaces instead of tabs.

Basically this line
[return JSON.stringify(values, null, '\t');](https://github.com/biesbjerg/ng2-translate-extract/blob/master/src/compilers/namespaced-json.compiler.ts#L10)

would become something like
`return JSON.stringify(values, null, this.spacer);`

**Comment by biesbjerg** [comment]
Could probably be implemented using options like `--indentation spaces/tabs --identation-size=2`.

Will keep this ticket open to be worked on in a future version :-)

**Comment by biesbjerg** [comment]
You can now specify custom indentation as an argument to the script :-)

**Comment by paulmfischer** [comment]
:+1: Thanks for this! I will give the new version a try soon.

**Comment by paulmfischer** [comment]
This works great with latest version! Thanks!
