### ISSUE TITLE
Service parser regexp is to greedy

### ISSUE THREAD

**Issue by FelixWessendorf** [biesbjerg/ngx-translate-extract#23]
The service parser ends up parsing:

`this.translate.get('Welcome to %s').map((translation: string) => {return translation.replace('%s', this.title); });`

with a match on `'Welcome to %s').map((translation: string) => {return translation.replace('%s'` when everything the above statement is written as one line.

**Comment by biesbjerg** [comment]
Please try using `-e` flag (the experimental AST Service parser). I'm considering making it the default.

**Comment by FelixWessendorf** [comment]
Thanks for your reply. I've tried the AST parser - without any luck. It's giving me

`INFO: Extracting strings from 'src\app'
ERROR: TypeError: Cannot read property 'parameters' of undefined
error Command failed with exit code 1.`

Maybe _with_ any luck, I will have time to figure out what's going on there. Sticking to the default parser till that happens. In order to have that work, you need to make sure the call to the translation service is the very last statement in a single line of code that uses literal strings.

**Comment by biesbjerg** [comment]
That error should be fixed in release 1.0.0. It happened in older versions of file did not have a constructor. Can you the newest release a try? (Package name changed to @biesbjerg/ngx-translate-extract)

**Comment by FelixWessendorf** [comment]
Thanks for the hint. I switched to the newest release (which I didn't know existed before you mentioned it). And it's all working now with the AST parser. Good work! It should have a bunch of unit tests and if they are okay you should definiteley make the AST parser default.

The regexp in the service parser still is to greedy. You can fix that with a question mark at the right place which makes reading the string non greedy like: `/(?:get|instant)\s*\(\s*(\[?\s*(['"`])([^\1\r\n]*?)\2\s*\]?)/`. But still.... you won't parse strings with correctly esacaped single quotes like `this.translate.instant('Welcome to Chicago O\'Hare')`. 

It is very difficult to get a good regexp for all sorts of appearances working - AST is the more natural, easier and safer way of searching for the translatable strings.

**Comment by biesbjerg** [comment]
Yeah, unfortunately making the regex non-greedy breaks a bunch of tests.

I think too, that AST is the way to go. I will probably release a v2.0 soon-ish, with AST as the default parser to get more feedback.

Using Angular's template parser to extract strings from templates would also be cool and less error prone, but it's pretty complicated stuff.

Closing this one, as I don't think it can be easily fixed by changing the regex and AST will be default in the near future.
