### ISSUE TITLE
Java Properties file syntax

### ISSUE THREAD

**Issue by wlievens** [biesbjerg/ngx-translate-extract#24]
Hello,

Do you have plans to implement java `.properties` files as a format? There are some nice tools (like IntelliJ IDEA's properties bundle editing) for editing properties file for i18n.

I wouldn't mind implementing it myself, though I'm not familiar enough yet with **npm** to set it all up. I would just fork in github, but then what?

Regards
Wouter

**Comment by biesbjerg** [comment]
Hi,

To be honest, no. I don't really want to maintain a bunch of code/compilers I don't personally use, so maybe it would be better to look into making the tool easily extendable, maybe by letting users define their own custom compilers (by importing from/extending the cli script).

If you have any ideas how to do this in a good way feel free to open a new ticket!

For now, your best bet is to fork this repo and add your own compiler.
