### ISSUE TITLE
AST Service Parser returns unknown error

### ISSUE THREAD

**Issue by chlupaccom** [biesbjerg/ngx-translate-extract#26]
Hello,

when I want to use AST Service Parser it looks like this: 

Jablicko:frontend jenik$ ngx-translate-extract -e -f pot -o src/assets/i18n/template.pot 
INFO: Extracting strings from '....'
ERROR: TypeError: Cannot read property 'text' of undefined

**Comment by biesbjerg** [comment]
Can you provide me with the file that results in the error so I can reproduce?
