### ISSUE TITLE
Can not use tanslate.instance in the same line more than once

### ISSUE THREAD

**Issue by Eeliya** [biesbjerg/ngx-translate-extract#27]
ng2-translate-extract can not extract the following text properly.

`console.log(this.translate.instant('some_text'), this.translate.instant('some_other'));`

**Comment by biesbjerg** [comment]
Please update to newest version.

`npm install @biesbjerg/ngx-translate-extract --save-dev`

**Comment by XoneFobic** [comment]
![image](https://cloud.githubusercontent.com/assets/3240922/24247303/6c565cea-0fcb-11e7-89fa-d822e826eeaa.png)

npm isn't updated, so will only install `0.6.0`

**Comment by biesbjerg** [comment]
Package was renamed, that's why. I've marked the package as deprecated, but doesn't seem like the user is notified when installing it.
