### ISSUE TITLE
Can not extract translation keys which conitain numbers

### ISSUE THREAD

**Issue by Eeliya** [biesbjerg/ngx-translate-extract#28]
`this.translate.instant('option.0');` This line cause the extractor to fail and I list of null instead the `0` as the key

**Comment by biesbjerg** [comment]
Which version are you using?

**Comment by Eeliya** [comment]
`"@biesbjerg/ngx-translate-extract": "^2.0.0",`

**Comment by biesbjerg** [comment]
Thanks. Which commands arguments are you using when extracting?

**Comment by Eeliya** [comment]
`ngx-translate-extract --input app/content --output path/to/file.json --format=namespaced-json --sort --clean`

**Comment by biesbjerg** [comment]
Thanks! I suspect the issue is in the NamedspacedJson compiler. Will take a closer look :-)
