### ISSUE TITLE
How does clean work?

### ISSUE THREAD

**Issue by challe** [biesbjerg/ngx-translate-extract#29]
Hi,

I'm currently trying out ngx-translate-extract by doing:
`ngx-translate-extract --input ./src --output ./src/assets/i18n/se.pot --clean --sort --format pot`

If I first have three strings in a .ts-file, and run the extractor, I see the three strings in my se.pot-file. So it all seems to be working fine. If I then remove one of the strings from my application and run the extractor again, is it supposed to remove the now not used string from the .pot-file, since it is no longer in use?
I got that impression from reading the documentation about `--clean`:
> Remove obsolete strings when merging

Thanks!

**Comment by biesbjerg** [comment]
That's exactly how it's supposed to work! Is that not what's happening?

**Comment by challe** [comment]
Nice! No, I still see all of the strings in `se.pot`. My output shows:

```
...
Extracted 1 strings


Saving: c:\dev\angular-base\src\assets\i18n\se.pot
- merged with 3 existing strings
- sorted strings
Done!
```

**Comment by biesbjerg** [comment]
Ah, I found the bug. It sneaked in after refactoring - fix coming right up!

**Comment by biesbjerg** [comment]
New NPM package published :-)
