### ISSUE TITLE
Extract and save to multiple files (.pot-files)?

### ISSUE THREAD

**Issue by challe** [biesbjerg/ngx-translate-extract#30]
Hi,

Should I be able to output to multiple files, even when using the pot-format? Currently, when doing:
`ngx-translate-extract --input ./src --output ./src/assets/i18n/{sv,nb,fi,da}.pot --clean --sort --format pot`

I get one output file named `{sv,nb,fi,da}.pot`.

**Comment by biesbjerg** [comment]
Which platform are you on? Your example works for me on osx, but not sure if expansion is supported on windows.

**Comment by challe** [comment]
I am on Windows. Oh, ok! I figured I needed multiple .pot-files, one per language. I'm fairly new to this, but the translation itself ends up in language specific .po-files (for example using Poedit).
So, using one "source-file" (.pot) should be fine, right?

**Comment by biesbjerg** [comment]
Yes, that's how I'm using it. Seems windows does not support expansion - you can specify multiple output paths though, if you want to extract to multiple files later on:-)

**Comment by challe** [comment]
Great, thanks :+1:

**Comment by cvaliere** [comment]
yes, you use one POT file

and then, you merge it into your PO files

like this, for instance:
`msgmerge fr.po keys.pot -U --backup=none --no-wrap`

**Comment by biesbjerg** [comment]
Closing as "works for me" :-)
