### ISSUE TITLE
'test...' extract as nested object

### ISSUE THREAD

**Issue by brianxu** [biesbjerg/ngx-translate-extract#33]
tested on v2.2.2
I'm not sure if it's intended but the following was extracted for a string 'test...':
```
"test": {
		"0": {
			"0": {
				"0": ""
			}
		}
	}
```

**Comment by brianxu** [comment]
use `--format json` fixed this issue for me, I guess I will close it.

**Comment by prophetw** [comment]
because you use the format name space 
this will regard "."  as a property of test
for e.g.  foo.bar   
this will format like 
foo:{
    bar:{}
}
