### ISSUE TITLE
Missing string values should be exported as null rather than an empty string

### ISSUE THREAD

**Issue by spiffyjr** [biesbjerg/ngx-translate-extract#35]
Fallbacks for ngx-translate don't consider an empty string as undefined (rightfully so, imo). I prose changing empty strings to export as `null` rather than `""`.

**Comment by Sharim** [comment]
Is this can be merged? It's really annoying because using `""` instead of `null` causing displaying literally nothing, however with `null` it's display value to translate which is better in my thinking, at least add it as param to extract command.

**Comment by biesbjerg** [comment]
Closed with https://github.com/biesbjerg/ngx-translate-extract/commit/97e8937709376dfb285d204d8b4bed142c4a0f57
