### ISSUE TITLE
Newlines being escaped

### ISSUE THREAD

**Issue by lahdekorpi** [biesbjerg/ngx-translate-extract#39]
Newlines piped into `translate` are being incorrectly escaped.

### To reproduce:
Add `{{ 'Line 1\nLine2' | translate }}` to a HTML being parsed.
Run `ngx-translate-extract --input ./src --output template.pot --clean --sort --format pot`

### Resulting pot-file:
```
msgid ""
"Line 1\\n"
"Line 2"
msgstr ""
```

### Expected result:
```
msgid "Line 1\nLine 2"
msgstr ""
```

**Comment by lahdekorpi** [comment]
A horribly nasty workaround:
```bash
sed -ie 's/\\\\n/\\n/g' template.pot
```

**Comment by biesbjerg** [comment]
This doesn't seem to be the case (anymore?)

The result I'm seeing, which seems to be correct?
```
msgid ""
"Line1\n"
"Line2"
```
