### ISSUE TITLE
[Feature Request] Custom default value for extracted keys

### ISSUE THREAD

**Issue by datrinh** [biesbjerg/ngx-translate-extract#40]
Hi, is it already possible to have some kind of default value for all extracted keys? Some kind of placeholder so that I spot values in the template that are missing.

**Comment by biesbjerg** [comment]
It is not possible at the moment. For now I would suggest using a custom Missing Translation Handler: https://github.com/ngx-translate/core#how-to-handle-missing-translations

**Comment by datrinh** [comment]
I am already using a custom handler for missing translations. The use case is a different one tho. That handler only sees strings that are not yet extracted. What I need is a default value for strings that already have been extracted. It's not high priority but I guess would be useful for some ppl like me.

**Comment by biesbjerg** [comment]
Ah, I don't experience this because I use a custom loader for po-files, and I don't load/add strings with empty translations.

https://github.com/biesbjerg/ngx-translate-po-http-loader/blob/master/src/index.ts#L49

**Comment by tommasnik** [comment]
+1

**Comment by karellodewijk** [comment]
For my use case it also makes a lot more sense to have a default value of null (which results in keeping the original string when a translation is missing), rather than "" (which results in the whole string being omitted). Then again, it's one find and replace every time I update the translation files.

**Comment by alesmit** [comment]
Replacing empty strings with `null` can be done with a simple node script:

```javascript
const fs = require('fs');
const path = require('path');

const config = {
  dir: './src/assets/i18n' // <-- your json translations directory
};

fs.readdirSync(config.dir).forEach(file => {
  if (path.extname(file) === '.json') {

    const filePath = `${config.dir}/${file}`;
    const json = fs.readFileSync(filePath, 'utf-8');
    const obj = JSON.parse(json);

    Object.keys(obj).forEach(key => {
      if (obj[key] === '') {
        obj[key] = null;
      }
    });

    const str = JSON.stringify(obj, null, '\t');
    fs.writeFileSync(filePath, str, 'utf-8');

  }
});
```
