### ISSUE TITLE
NPM package v2.2.2 contains old template parser regex

### ISSUE THREAD

**Issue by Ben305** [biesbjerg/ngx-translate-extract#41]
The currently published package v2.2.2 contains the old regex in pipe.parser.js: 
```var regExp = /(['"`])([^>\1\r\n]*?)\1\s*\|\s*translate/g;```

It should be ```var regExp = /(['"`])((?:(?!\1).|\\\1)+)\1\s*\|\s*translate/g;```

**Comment by biesbjerg** [comment]
Thanks!

v2.2.3 published to npm.
