### ISSUE TITLE
Pipe translated multiline strings are not captured

### ISSUE THREAD

**Issue by artjoman** [biesbjerg/ngx-translate-extract#45]
Multiline strings translated with a pipe are not being captured, see example [HERE](https://regex101.com/r/fE8Xqx/2)

A solution would be to rebuild the regex to match multiline with a flag \s\S as displayed in this example [HERE](https://regex101.com/r/fE8Xqx/1)

**Comment by biesbjerg** [comment]
What would you expect the extracted strings to look like? By including `\r*\n*` we will capture multiline strings, but that includes the actual line breaks and indentation.

Here's a test, that passes when including `\r*\n*` in the regex:

```ts
	it('should extract multiline strings', () => {
		const contents = `
			{{"hello
			world"|translate}}
			{{"hello bla bla bla
			bla lba bla bla
			world 2"|translate}}
			{{"hello bla bla bla
			world 3"|translate}}
		`;
		const keys = parser.extract(contents, templateFilename).keys();
		expect(keys).to.deep.equal(['hello\n\t\t\tworld', 'hello bla bla bla\n\t\t\tbla lba bla bla\n\t\t\tworld 2', 'hello bla bla bla\n\t\t\tworld 3']);
	});
```

What do you think?

**Comment by biesbjerg** [comment]
Since 5.0.0 AST is used for parsing templates.
