### ISSUE TITLE
Strings not extracted if a file contains multiple exports

### ISSUE THREAD

**Issue by lahdekorpi** [biesbjerg/ngx-translate-extract#46]
If a file contains multiple exports, only the strings in the first one get extracted.

Example:
```typescript
import { Injectable } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
export class Stuff {
	thing: string;
	constructor(thing: string) {
		this.thing = thing;
	}
}
@Injectable()
export class AuthService {
	constructor(public translate: TranslateService) {
		console.log(this.translate.instant("Hello!"));
	}
}
```

`Hello!` Doesn't get extracted.  
After removing the Stuff class it will.

**Comment by biesbjerg** [comment]
This is by design per Angular's style guide: https://angular.io/styleguide#!#01-01

PR to add this enhancement is welcome though.
