### ISSUE TITLE
--marker ERROR: Unknown option 

### ISSUE THREAD

**Issue by xsoroton** [biesbjerg/ngx-translate-extract#47]
--marker is Unknown option, please fix your Docs

**Comment by biesbjerg** [comment]
Please paste full output of your error. Also version

**Comment by xsoroton** [comment]
"0.6.0"
error:
` ERROR: Unknown option --marker`

**Comment by biesbjerg** [comment]
Install latest version, 2.3.1:

npm install @biesbjerg/ngx-translate-extract --save-dev

And please be more detailed when opening future issues. 🙃

**Comment by xsoroton** [comment]
oh, ok...
npm have 0.6.0 as latest, it's where all confusion start ;)
https://www.npmjs.com/package/@biesbjerg/ng2-translate-extract
