### ISSUE TITLE
Breaks down a string into several if nested html content in it

### ISSUE THREAD

**Issue by OzoTek** [biesbjerg/ngx-translate-extract#51]
Hello,

I encountered an issue while using the extraction for strings containing html, for instance :
`<div translate>This is my <b>string</b> to translate</div>`

I would expect translating `This is my <b>string</b> to translate` and just put the tags back in the translations as well, which is what I used to do before switching to Angular 2.
But it now gives me 2 strings : `This is my ` and ` to translate`, which is not really convenient when translating sentences.

Is there another solution for doing something like this?

Thanks.

**Comment by PapyElGringo** [comment]
Any update on this?

**Comment by PapyElGringo** [comment]
Or work around?

**Comment by cojack** [comment]
@biesbjerg ping

**Comment by biesbjerg** [comment]
Fixed in next version
