### ISSUE TITLE
Multiline sentence in html breaks into multiple line in msgid

### ISSUE THREAD

**Issue by akhildhanuka** [biesbjerg/ngx-translate-extract#52]
If I have a sentence for translation in html like - 

"There are currently no students in this class. The good news is, adding students is really easy! Just use the options at the top." represented in multiline because of linting condition then the translation key becomes 
"There are currentlyno students in this class. The good news is, adding "
"students is really easy! Just use the options at the top."

It should not break the keys unless a <br> is mentioned in the html. 

Any work around for this issue?

**Comment by biesbjerg** [comment]
Hello!

Please provide template and the generated po-file and I will take a look when I get some free time

**Comment by akhildhanuka** [comment]
Thanks biesbjerg. Attached a sample html + po to replicate the issue.

The div which has the long sentence - 

    <div *ngIf="!isLoading && studentsToGrid && studentsToGrid.length == 0" class="no-students" mt-rtl translate>There
        are currentlyno students in this class. The good news is, adding students is really easy! Just use the options
        at the top.
    </div>


[ngx.zip](https://github.com/biesbjerg/ngx-translate-extract/files/1059712/ngx.zip)

**Comment by akhildhanuka** [comment]
@biesbjerg - any luck with this issue?

**Comment by biesbjerg** [comment]
Does it actually causes any trouble?

I found [this](http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html):

> When a message is long or contains some logical line-breaks, its original and translation strings may be wrapped in the PO file (with wrapping boundary usually at column 80), such as this:
> 
> #: indimenu.cpp:96
> msgid ""
> "No INDI devices currently running. To run devices, please select devices "
> "from the Device Manager in the devices menu."
> msgstr ""
>
> This wrapping is entirely invisible to the consumer of the PO file.

Closing, since this is how it's supposed to work.
