### ISSUE TITLE
Allow clean to ignore specific key

### ISSUE THREAD

**Issue by BenDevelopment** [biesbjerg/ngx-translate-extract#54]
It would be nice to have the possibility to mark some keys to tell the script to not clean them if they are no longer found on the project.

For example:
```
{
	"Hello": "Bonjour",
	"Bye": "Au revoir",
	"Eat": "Manger",
	 "Omelette with cheese": "Omelette au fromage" #clean_ignore
}
```
If I run the script, if `"Omelette with cheese"` is not found on the project, it will not remove it because of the `#clean_ignore` annotation.

It can be usefull for dynamic content translation.

**Comment by bedag-moo** [comment]
Why can't you use the [marker function](https://github.com/biesbjerg/ngx-translate-extract#mark-strings-for-extraction-using-a-marker-function)?

**Comment by jscti** [comment]
+1 that.

For example, if you have an enum server side (say a "user role") and want to handle its traduction client side, you'll want to have in your translation file :
```
{
    "userRole": {
        "admin" : "Administrator",
        "visitor" : "Visitor"
    }
}
```

Template side or in .ts you'll want to concat `'userRole.' + userRoleFromServer` to retrieve translation. But how do you handle this with the `--clean` option ?

There could be something like a joker like : `_('userRole.*')` that tell cleaning parser to ignore this key

**Comment by BenDevelopment** [comment]
What I understood since my post is that backend translation should be provided by backend. Frontend translation should only manage static front texts. The backend should have a service which return all the backend translations or a service which return translation for a given key/text.
The cleaner solution (in my opinion) is to tell your backend to return your objects (json) translated. You can tell your bakcend what language it should return within the user session's settings.

**Comment by jscti** [comment]
backend key + client translation is just an example here to point out (like you did) something missing with dynamic translations

**Comment by BenDevelopment** [comment]
Yes.
I've just noticed @bedag-moo comment, he is right, we can use [marker function](https://github.com/biesbjerg/ngx-translate-extract#mark-strings-for-extraction-using-a-marker-function) to achieve that.

**Comment by jscti** [comment]
Saw that comment too but, How ?
I did use it, but had to hardcode it like `_('userRole.admin'); _('userRole.visitor');`. But what if I have 10/50/n values ?

**Comment by BenDevelopment** [comment]
Maybe I'm missing something but I think in any case you have to hardcode every terms. 
I can't see any other solution without adding a new functionality to this project.

**Comment by bagage** [comment]
At least adding the wildcard operator would allow to use it as `_('userRole.*');`, which would avoid having to hardcode all possible values twice? 

Is there any update on this topic? 

@BenDevelopment and @jscti, did you solve that issue somehow else?

**Comment by bedag-moo** [comment]
The problem with a pattern is that ng-translate-extract also ensures that all translation files have the same keys. How would ngx-translat-extract resolve differences among translation files when it just has a pattern? 

Personally, I think the perfect solution would be to derive the set of keys from an enum (or union type), but that requires significant extension of ngx-translate-extract ...

And yes, we just use the marker function for now. I sucks having to duplicate enum values, but it is less painful than any alternative that I am aware of.

**Comment by biesbjerg** [comment]
You should use the marker function to add/keep strings not passed directly to any methods of translateService. Closing :)

**Comment by jscti** [comment]
@biesbjerg 
Hi there. I really think this should be reopened ... 

With dynamic values, marker function is more a workaround than a clean way to do it and it's really a pain to hardcode all the dynamic values just to make them ignored by this extractor ...

A simple joker-based-ignore would be some much simple ... `_('DYNAMIC_KEY.*')`
Server could then easily send me `DYNAMIC_KEY.VAL1` or  `DYNAMIC_KEY.VAL2` or `DYNAMIC_KEY.VAL999` etc ...

**Comment by oeem1011** [comment]
I also hardly need to translate my Enum Values...
