### ISSUE TITLE
Keep arrays in json files instead of converting them into objects

### ISSUE THREAD

**Issue by CodeAndWeb** [biesbjerg/ngx-translate-extract#58]
I'd like to use the following code to add multiple paragraphs to a page:

    <p *ngFor="let line of ('multi-paragraph' | translate)">
        {{line}}
    </p>
    
ngx-translate-extract finds the 'multi-paragraph' and adds it to the json files. So far it's ok.
I now edit the file using an array:

    {
    	"multi-paragraph": [
    		"paragraph1",
    		"paragraph2",
    		"paragraph3"
    	]
    }
    
The app works as expected and displays all paragraphs...

Running `npm extract` changes the content of the json files to

    {
    	"multi-paragraph": {
    		"0": "paragraph1",
    		"1": "paragraph2",
    		"2": "paragraph3"
    	}
	}
	
The result is a json object which can't be processed by ngFor.

It would really be great if ngx-translate-extract would not change the arrays into objects...

**Comment by penniath** [comment]
+1

**Comment by penniath** [comment]
Any updates on this issue?

**Comment by narek-mac** [comment]
In my case the array is deleted completely and added empty string but other strings are kept as is.

**Comment by CodeAndWeb** [comment]
I used `<div [innerHtml]="">` with a pre-formatted block instead. Was much easier than iterating over the paragraphs after all...
