### ISSUE TITLE
Format indentation doesn't work on windows for whitespace characters

### ISSUE THREAD

**Issue by olivermue** [biesbjerg/ngx-translate-extract#62]
If you try to set the format indentation on a windows machine, the given arguments will be misunderstood. By trying the examples from documentation you'll get malformed json files.

`ngx-translate-extract -i ./src -o ./src/i18n/en.json --format-indentation $'\t'` outputs the following content:

	{
	$'"COUNTER": "",
	$'"ENGLISH": "",
	$'"HOME": "",
	$'"HOME_FEATURE_LIST_TITLE": "",
	$'"HOME_ISSUES_TITLE": "",
	$'"NORWEGIAN": "",
	$'"SWITCH_LANGUAGE": ""
	}

`ngx-translate-extract -i ./src -o ./src/i18n/en.json --format-indentation ' '`outputs the following content:

    {
    '"COUNTER": "",
    '"ENGLISH": "",
    '"HOME": "",
    '"HOME_FEATURE_LIST_TITLE": "",
    '"HOME_ISSUES_TITLE": "",
    '"NORWEGIAN": "",
    '"SWITCH_LANGUAGE": ""
    }

It seems, that the command line arguments will be split at each whitespace character and the indentation parameter gets the characters right before the whitespace character that should be taken for indentation (in first case `$'`, in second case `'`).

This happens if I add the above examples to my package.json within the scripts section. If I'm going to call your tool directly from command line
`.\node_modules\.bin\ngx-translate-extract -i ./src -o ./src/i18n/en.json --clean --sort --format namespaced-json --format-indentation '    '`
it works correctly.

So it seems to be more a problem of npm (I'm using 3.10.10 from node 6.10.2) and/or windows (Win10). But maybe you have an idea on how to fix it or whom to blame.

**Comment by sten82** [comment]
Try `--format-indentation \" \" ` that helped my on windows 10 with node 6.9.4 and npm 5.4.1

**Comment by ThomasGoris** [comment]
`--fi \u00A0\u00A0` works as well on windows 8.1, npm 4.1.2.

**Comment by olivermue** [comment]
By using @sten82 advice, the working entry within my package.json on my windows machine is:

    "scripts": {
      "extract": "ngx-translate-extract --input ./ClientApp --output ./wwwroot/assets/i18n/en.json --output ./wwwroot/assets/i18n/de.json --clean --sort --format namespaced-json --format-indentation=\"    \"",
    }
