### ISSUE TITLE
get() and instant() don't get extracted

### ISSUE THREAD

**Issue by tehXor** [biesbjerg/ngx-translate-extract#64]
In the following code (and some variations of it) `instant()` doesn't get extracted (and the same applies if I try to use `get()` promises).

Is this a bug or not supported?

If not supported it would be a good enhancement.

Also I only looked shortly in the code and it seems to me that it's not using regex like I was used it from older/other grunt/gulp extraction scripts out there for other use cases. Has this a specific reason and or would it be bad to parse files simply for regex patterns? I'm asking this as it is a quite big requirement for me to be flexible in extractions in a project (and regex seems to me fairly less complex and easy to add custom patterns) and am currently thinking about working with `ngx-translate-extract` and maybe extending it a little or to build a mere regex based solution which outputs ngx-translate valid JSON...

```
import { Component, Inject, OnInit } from '@angular/core';
import { FormBuilder, Validators, FormControl } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { IonicPage } from 'ionic-angular';

@IonicPage({
    segment: 'some-page'
})
@Component({
    selector: 'some-page-selector',
    templateUrl: 'some-page.html'
})
export class RegisterView implements OnInit {
    newForm: any;

    constructor(
      @Inject('Window') window,
      private formBuilder: FormBuilder,
      private tl8: TranslateService
    ) {
        let ctrl = this;

        let someFormFieldForDynamicGeneration = new FormControl('', [Validators.required]);
        someFormFieldForDynamicGeneration['type'] = "text";
        someFormFieldForDynamicGeneration['label'] = tl8.instant("Some random field");

        this.newForm = this.formBuilder.group({
            'someFormFieldForDynamicGeneration': someFormFieldForDynamicGeneration,
        });
    }

    ngOnInit() {
		// ...
    }
	
	//...
}
```

**Comment by biesbjerg** [comment]
Hello,

Your use-case is not supported (at least not at the moment). Related ticket: https://github.com/biesbjerg/ngx-translate-extract/issues/50

The reason regex is no longer used is because it's not very reliable compared to parsing the code into an AST, but it can be a bit more complicated.

Please change `tl8.instant("Some random field");` to `this.tl8.instant("Some random field");` to work around your specific issue.

**Comment by tehXor** [comment]
In case someone stumbles upon this, we ended up using https://github.com/angular-translate/grunt-angular-translate. This worked (for our project) without any modifications, also we were using the most recent Ionic / Angular versions. It also comes with an option for custom regex patterns out of the box (see their examples in their [Gruntfile.js](https://github.com/angular-translate/grunt-angular-translate/blob/master/Gruntfile.js)). Implementing some regex patterns (which worked like intended in our case) seemed like the less complex approach than extending this modules to support extraction in non constructors functions, static functions, and various other places.
