### ISSUE TITLE
deprecate @biesbjerg/ngx-translate-extract@2.3.2 › chalk@2.0.1 Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.

### ISSUE THREAD

**Issue by mygu** [biesbjerg/ngx-translate-extract#67]
I got this error at `npm install`
This error can be ignored? 
Will it have any impact?

**Comment by Chuvisco88** [comment]
+1

**Comment by raphael22** [comment]
+1

**Comment by mkurcius** [comment]
+1

**Comment by tiberiuzuld** [comment]
+1

**Comment by gervasiocaj** [comment]
There are no release notes between chalk v2.0.1 and v2.1.0. To close the issue, the changes available at https://github.com/chalk/chalk/compare/v2.0.1...chalk:v2.1.0 must be reviewed.

**Comment by DavidMarquezF** [comment]
I tried updating the version and running the script in my project and it still doesn't add template literals

**Comment by biesbjerg** [comment]
Chalk is not used in the next release, closing.
