### ISSUE TITLE
Parse methods get and instant doesn't work

### ISSUE THREAD

**Issue by gilnoy** [biesbjerg/ngx-translate-extract#69]
I'm trying to parse my .ts files that have .get() & .instant() but i get 0 strings extracted - how can i make it work? any special configuration?

**Comment by didacrios** [comment]
Can you share the extract command that you are using? I'am currently having no problems extracting instants

**Comment by sgwatgit** [comment]
@gilnoy Are you using variables in your `get()` and `instant()` calls? I don't believe that's supported.

Here is an npm script that is working for me just fine
`ngx-translate-extract -i ./src -o ./src/i18n/en-US.po -c -s -f pot`

Are you on Windows? There seems to be an issue with globs on Windows https://github.com/biesbjerg/ngx-translate-extract/issues/53#issuecomment-314087788
