### ISSUE TITLE
Extract child tags

### ISSUE THREAD

**Issue by PapyElGringo** [biesbjerg/ngx-translate-extract#71]
Hello thanks for your work on this!

I have an issue extracting tags with embedded tags like this:

```
<div translate>
    Hello <strong>world</strong> hope you are all fine.
</div>
```

I expected get `Hello <strong>world</strong> hope you are all fine.` in my .pot file instead I get 2 entries:

`Hello `
` hope you are all fine.`

It's skipping totally the `<strong>world</strong>`.

Any idea?

**Comment by PapyElGringo** [comment]
duplicate of #52...

sorry

**Comment by biesbjerg** [comment]
Fixed in next version
