### ISSUE TITLE
Ignore glob for path

### ISSUE THREAD

**Issue by un33k** [biesbjerg/ngx-translate-extract#72]
[x] feature request

**version**
    "@biesbjerg/ngx-translate-extract": "^2.3.2",

A way to ignore globs or paths. For example ignoring all files ending with /**/*.spec.ts

**Example:**  
ngx-translate-extract --input ./src --output ./src/assets/i18n/*.json --ignore ./src/**/*.spec.ts --clean --sort --format namespaced-json

**Comment by amnporter** [comment]
Is there a way to do this and directories as well?

**Comment by biesbjerg** [comment]
Should be possible in the next release: https://github.com/biesbjerg/ngx-translate-extract/commit/b813ec0063f45af918177fa9d059ef823837af80
