### ISSUE TITLE
Empty translation strings

### ISSUE THREAD

**Issue by Alir3z4** [biesbjerg/ngx-translate-extract#73]
I'm trying to run it on the Window but it gets empty results.
I ran the command:
```
ngx-translate-extract -i ./src -o ./src/assets/i18n/{da,en,fr}.json
```

and it simply created a file named `/src/assets/i18n/{da,en,fr}.json` and with the translation keys but empty values:

```
{
	"BACK_BUTTON_TEXT": "",
	"LOGIN_ERROR": "",
	"SIGNUP_ERROR": "",
	"WELCOME_TITLE": "",
	"LOGIN": "",
	"SIGNUP": "",
	"POSTS_TITLE": "",
	"LOGIN_TITLE": "",
	"USERNAME": "",
	"PASSWORD": "",
	"LOGIN_BUTTON": "",
	"SIGNUP_TITLE": "",
	"NAME": "",
	"EMAIL": "",
	"SIGNUP_BUTTON": "",
	"TUTORIAL_SKIP_BUTTON": "",
	"TUTORIAL_SLIDE4_TITLE": "",
	"TUTORIAL_CONTINUE_BUTTON": ""
}
```

My environment:

* Version: 2.3.2
* OS: Windows
* Node version v8.1.2

**Comment by lexzhukov** [comment]
Same issue.

**Comment by kareljuricka** [comment]
From where it should get translation string values? I understand that key is from translate pipe example: {{ 'HELLO' | translate }} but value? I don't get it.

**Comment by takahser** [comment]
@Alir3z4 I think this feature is not part of this package.

@kareljuricka With Angular Core it works, [see docs](https://angular.io/guide/i18n#mark-text-with-the-i18n-attribute). However, in that case it's not a directive that is used but instead an attribute that acts as a marker and is removed after translating the texts.

**Comment by biesbjerg** [comment]
In next release a flag is added to have translation values be the same as keys by default.
