### ISSUE TITLE
Extract translatable strings with a custom prefix

### ISSUE THREAD

**Issue by mnasyrov** [biesbjerg/ngx-translate-extract#77]
A feature request.

Support extracting translatable strings which have a custom prefix for marking.
Example string: ```'i18n:hello-world'```
Usage example: ```ngx-translate-extract --stringPrefix 'i18n:'```

**Comment by biesbjerg** [comment]
I'm not sure I understand. This sounds like a use that the `marker`-function already supports?

Closing for now.
