### ISSUE TITLE
Custom patterns not working - ngx-translate-extract --patterns ['**/*.js']

### ISSUE THREAD

**Issue by PDawda** [biesbjerg/ngx-translate-extract#78]
I am trying to extract keys from an transpiled angular npm package. My HTML template is inlined in all components in template attribute. 
By giving a pattern to extract from JS files extracts 0 keys:

The Command being tried is as below:
 ngx-translate-extract --patterns ['**/*.js'] --input ./node_modules/@digital/ --output ./src/assets/i18n/en-US.json --clean --sort --format namespaced-json

Extracted 0 strings is output.

Please guide what am I missing.

**Comment by PDawda** [comment]
Was trying Incorrect way of adding patterns, below way worked for me.
ngx-translate-extract -p /**/*.js

**Comment by PDawda** [comment]
This command is not working completely, if there is transpiled JS version of a component with inline HTML templates inside JS version, the pattern extracts keys only from template and is skipping the code keys for eg: translate.instant or translate.get

**Comment by lee-da** [comment]
Adding a custom pattern works like this:
` -p /**/*.html /**/*.ts /**/*.php`

**Comment by biesbjerg** [comment]
Please use the following since v5:

`ngx-translate-extract --input ./node_modules/@digital/**/*.js --output ./src/assets/i18n/en-US.json --clean --sort --format namespaced-json`
