### ISSUE TITLE
Add a way to exclude dynamic translation

### ISSUE THREAD

**Issue by jeremyputeaux** [biesbjerg/ngx-translate-extract#80]
[x] feature request

I'm using `this.translate.get(variable)` with a dynamic value as a parameter.
Everytime I try an extract, I get `SKIP: Unknown argument type: etc...`. I know it's expected but is there a way to avoid this `this.translate.get(variable)` to be parsed?

**Comment by dimi-nk** [comment]
Same problem here. I concatenate 2 strings to make up the translation key, e.g. `PAYMENT_TYPE.${paymentType.toLocaleUpperCase()}` and the library tries to extract `PAYMENT_TYPE.`

**Comment by segux** [comment]
Are anyone working on this issue?

**Comment by biesbjerg** [comment]
Fixed in next release :-)

**Comment by beck** [comment]
Apologies to comment on a closed issue, which release?
Would love to peek at the diff that resolves this issue.
