### ISSUE TITLE
Weird handling of dots in translation tokens.

### ISSUE THREAD

**Issue by karellodewijk** [biesbjerg/ngx-translate-extract#82]
Whenever a translation string contains a dot something like this gets generated. 

{{ 'inc. IP' | translate }} becomes:
"Inc": {
	" IP": "Geinc. up"
},

It's weird, but not a huge issue because it does actually work. "Inc. IP" does get replaced by "Geinc. up".

When the original ends with a dot it gets even weirder.

{{ 'Mr.' | translate }} becomes:
"Mr": {
	"0": "Dhr."
},

And now it doesn't work any more "Mr." does not get translated to "Dhr.".

**Comment by bsalesc** [comment]
You should consider the tag as a variable, so it's right!

**Comment by karellodewijk** [comment]
ngx-translate however does not put such restrictions on variables, it would be perfectly happy with:

{
  "Inc. IP": "Geinc. up",
  "Mr.": "Dhr."
}

**Comment by biesbjerg** [comment]
Sounds like you're using `--format namespaced-json` which treats `.` as a namespace and will nest strings. 

Try using `--format json` instead.
