### ISSUE TITLE
How to exclude folders from --input flag?

### ISSUE THREAD

**Issue by amnporter** [biesbjerg/ngx-translate-extract#93]
I've made numerous attempts to exclude a folder and keep getting an error stating that the folder doesn't exist. Has anyone been able to do this successfully?

Tried:
```
-i ./src/app/ !./src/app/playground
-i ./src/app/ !./**/**/playground
-i ./src/app/ ./src/app/!(playground)
```

**Comment by alesmit** [comment]
@amnporter did you find any solutions here?

**Comment by amnporter** [comment]
@alesmit, I have not found a solution for this. I also haven't successfully implemented the --patterns flag to omit .spec.ts and .page.ts files from extractions.

**Comment by alesmit** [comment]
@amnporter I know it may sound nasty but I ended up using a node script and executing `ngx-translate-extract` through it multiple times with different parameters.

**Comment by amnporter** [comment]
@alesmit, that does sound nasty. I'm just running through our entire project and fixed issues in directories that we originally didn't want to include. Either way, we're up and running!

**Comment by biesbjerg** [comment]
Should be possible using:

ngx-translate-extract -i './src/**/!(*.spec).{ts,html}' -o strings.json

Extract from ts, html, excluding files with ".spec"

**Comment by chrismclarke** [comment]
In case anyone else has this issue, the easiest way I found to omit an entire folder path was to create a separate script that would temporarily move the folder out of the src directory, run the ngx-translate-extract script, and then move back. Not too messy and should at least be fairly efficient.

**Comment by UchihaYuki** [comment]
the solution doesn't work in windows?
